export const workers = [
  { id: 1, name: "Adelmo Herrera", company: "Construction", crew: "Omar", wage: null, ot_wage: null },
  { id: 2, name: "Alexis Morales", company: "Construction", crew: "Waldo", wage: 16, ot_wage: 24 },
  { id: 3, name: "Alfredo Martinez", company: "Landscape", crew: "Moises", wage: 17, ot_wage: 25.5 },
  { id: 4, name: "Andres Dorantes", company: "Landscape", crew: "Wilson", wage: 15, ot_wage: 22.5 },
  { id: 5, name: "Antonio Martinez", company: "Landscape", crew: "Noel", wage: 17, ot_wage: 25.5 },
  { id: 6, name: "Antonio Ruiz", company: "Construction", crew: "Miscellaneous", wage: null, ot_wage: null },
  { id: 7, name: "Antonio Morales", company: "Landscape", crew: "Noel", wage: 14, ot_wage: 21 },
  { id: 8, name: "Axel Rodriguez", company: "Landscape", crew: "Ricardo", wage: 14, ot_wage: 21 },
  { id: 9, name: "Baldemar Ajpacaja Chiyal", company: "Landscape", crew: "Erving", wage: 17, ot_wage: 25.5 },
  { id: 10, name: "Brayan Lucero", company: "Construction", crew: "Omar", wage: null, ot_wage: null },
  { id: 11, name: "Carlos Andrade", company: "Landscape", crew: "Wilson", wage: 16, ot_wage: 24 },
  { id: 12, name: "Carlos Hernandez", company: "Construction", crew: "Jose L", wage: 23, ot_wage: 34.5 },
  { id: 13, name: "Carlos Limon", company: "Construction", crew: "Black", wage: 19, ot_wage: 28.5 },
  { id: 14, name: "Carlos Lopez", company: "Construction", crew: "Tony", wage: null, ot_wage: null },
  { id: 15, name: "Cesar Martinez", company: "Landscape", crew: "Erving", wage: 17, ot_wage: 25.5 },
  { id: 16, name: "Cesar Romero", company: "Landscape", crew: "Cesear Old", wage: null, ot_wage: null },
  { id: 17, name: "Christian Rivera", company: "Construction", crew: "Jairo", wage: 20, ot_wage: 30 },
  { id: 18, name: "Delfino Gamez", company: "Landscape", crew: "Defino", wage: 25, ot_wage: 37.5 },
  { id: 19, name: "Douglas Coronado", company: "Landscape", crew: "Defino", wage: 17, ot_wage: 25.5 },
  { id: 20, name: "Erving Rojas Ruiz", company: "Landscape", crew: "Erving", wage: 21, ot_wage: 31.5 },
  { id: 21, name: "Eufemio Martinez", company: "Landscape", crew: "Noel", wage: 17, ot_wage: 25.5 },
  { id: 22, name: "Fernando Cortez", company: "Construction", crew: "Marco", wage: 24, ot_wage: 36 },
  { id: 23, name: "Gabino Galvan", company: "Construction", crew: "Gambino", wage: 101400, ot_wage: 0, salary: true },
  { id: 24, name: "Gabriel Delgado", company: "Landscape", crew: "Moises", wage: null, ot_wage: null },
  { id: 25, name: "Gabriel Ruiz-Paramo", company: "Construction", crew: "Black", wage: 21, ot_wage: 31.5 },
  { id: 26, name: "Giovani Garcia", company: "Construction", crew: "Jairo", wage: 18, ot_wage: 27 },
  { id: 27, name: "Hector Calles", company: "Construction", crew: "Marco", wage: 22, ot_wage: 33 },
  { id: 28, name: "Henry Hernandez", company: "Landscape", crew: "Moises", wage: 20, ot_wage: 30 },
  { id: 29, name: "Hugo Herrera-Rivera", company: "Construction", crew: "Hugo", wage: 25, ot_wage: 37.5 },
  { id: 30, name: "Javier Figueroa", company: "Construction", crew: "Waldo", wage: 21, ot_wage: 31.5 },
  { id: 31, name: "Jeronimo Carbajal Arenas", company: "Construction", crew: "Tony", wage: 18, ot_wage: 27 },
  { id: 32, name: "Jesling Bravo", company: "Landscape", crew: "Wilson", wage: 14.5, ot_wage: 21.75 },
  { id: 33, name: "Jesus Cameras", company: "Construction", crew: "Gambino", wage: 22, ot_wage: 22 },
  { id: 34, name: "Jose Penaloza", company: "Construction", crew: "Jose L", wage: 29, ot_wage: 43.5 },
  { id: 35, name: "Jose Reyes", company: "Construction", crew: "Miscellaneous", wage: 18, ot_wage: 27 },
  { id: 36, name: "Jose Contreras", company: "Construction", crew: "Jairo", wage: 18.5, ot_wage: 27.75 },
  { id: 37, name: "Jose Delgadillo", company: "Construction", crew: "Gambino", wage: 22, ot_wage: 22 },
  { id: 38, name: "Jose Diaz", company: "Landscape", crew: "Cesear Old", wage: null, ot_wage: null },
  { id: 39, name: "Jose Hernandez", company: "Construction", crew: "Yard", wage: 18.5, ot_wage: 27.75 },
  { id: 40, name: "Jose Munguia", company: "Landscape", crew: "Wilson", wage: 18, ot_wage: 27 },
  { id: 41, name: "Josue Maldonado", company: "Landscape", crew: "Defino", wage: 14, ot_wage: 21 },
  { id: 42, name: "Juan Alvarez", company: "Construction", crew: "Tony", wage: 90000, ot_wage: null, salary: true },
  { id: 43, name: "Julio Martinez", company: "Construction", crew: "Miscellaneous", wage: 20, ot_wage: 30 },
  { id: 44, name: "Kennel Maradiaga", company: "Construction", crew: "Martin", wage: 20.5, ot_wage: 30.75 },
  { id: 45, name: "Kevin Davila", company: "Construction", crew: "Omar", wage: null, ot_wage: null },
  { id: 46, name: "Kevin Manzanares", company: "Landscape", crew: "Defino", wage: 18, ot_wage: 27 },
  { id: 47, name: "Leroy III Nelson", company: "Construction", crew: "Driver", wage: 20, ot_wage: 30 },
  { id: 48, name: "Luis Delgadillo", company: "Construction", crew: "Black", wage: 25, ot_wage: 37.5 },
  { id: 49, name: "Luis Martinez", company: "Landscape", crew: "Erving", wage: 17, ot_wage: 25.5 },
  { id: 50, name: "Luis Castrejon", company: "Construction", crew: "Marco", wage: 22, ot_wage: 33 },
  { id: 51, name: "Luis Escalante", company: "Construction", crew: "Martin", wage: 20, ot_wage: 30 },
  { id: 52, name: "Luis Limon", company: "Construction", crew: null, wage: 101400, ot_wage: null, salary: true, role: "supervisor" },
  { id: 53, name: "Luis Pavon Lopez", company: "Construction", crew: "Black", wage: 24, ot_wage: 36 },
  { id: 54, name: "Marco Gomez", company: "Construction", crew: "Waldo", wage: 22, ot_wage: 33 },
  { id: 55, name: "Marco Mandujano", company: "Construction", crew: "Martin", wage: 20, ot_wage: 30 },
  { id: 56, name: "Marco Vazquez Rodriguez", company: "Construction", crew: "Marco", wage: 28.5, ot_wage: 42.75 },
  { id: 57, name: "Martin Mendez", company: "Construction", crew: "Martin", wage: 113200, ot_wage: 0, salary: true },
  { id: 58, name: "Martin Morales", company: "Landscape", crew: "Noel", wage: 16.5, ot_wage: 24.75 },
  { id: 59, name: "Moises Torrez", company: "Landscape", crew: "Moises", wage: 21, ot_wage: 31.5 },
  { id: 60, name: "Moises Rivera", company: "Construction", crew: "Miscellaneous", wage: 18, ot_wage: 27 },
  { id: 61, name: "Nestor Lopez", company: "Construction", crew: "Black", wage: 14, ot_wage: 21 },
  { id: 62, name: "Nobel Lazo", company: "Landscape", crew: "Nobel", wage: 24.5, ot_wage: 36.75 },
  { id: 63, name: "Noel Morales", company: "Landscape", crew: "Moises", wage: 17, ot_wage: 25.5 },
  { id: 64, name: "Norlan Orozco", company: "Construction", crew: "Gambino", wage: 22, ot_wage: 22 },
  { id: 65, name: "Octavio Roman", company: "Construction", crew: "Cesear", wage: 17, ot_wage: 25.5 },
  { id: 66, name: "Omar Cortez", company: "Construction", crew: "Omar", wage: null, ot_wage: null },
  { id: 67, name: "Oswaldo Chavez", company: "Construction", crew: "Waldo", wage: 27, ot_wage: 40.5 },
  { id: 68, name: "Pablo Urgate", company: "Construction", crew: "Gambino", wage: 22, ot_wage: 22 },
  { id: 69, name: "Patricio Gonzalez", company: "Landscape", crew: null, wage: 23, ot_wage: 34.5, role: "manager" },
  { id: 70, name: "Pedro Maldonado", company: "Construction", crew: "Black", wage: 18, ot_wage: 27 },
  { id: 71, name: "Ricardo Pinzon", company: "Landscape", crew: "Ricardo", wage: 18, ot_wage: 27 },
  { id: 72, name: "Ronald Mendoza-Goitia", company: "Construction", crew: "Jose L", wage: 23, ot_wage: 34.5 },
  { id: 73, name: "Rony Hernandez", company: "Construction", crew: "Martin", wage: 20.51, ot_wage: 30.765 },
  { id: 74, name: "Rosendo De La Cruz", company: "Landscape", crew: "Defino", wage: 16, ot_wage: 24 },
  { id: 75, name: "Samuel Oliva Ramirez", company: "Landscape", crew: "Erving", wage: 17, ot_wage: 25.5 },
  { id: 76, name: "Santo Varela", company: "Landscape", crew: "Defino", wage: 16.5, ot_wage: 24.75 },
  { id: 77, name: "Santos Rodriguez", company: "Landscape", crew: "Wilson", wage: null, ot_wage: null },
  { id: 78, name: "Ulber Pineda", company: "Construction", crew: "Jairo", wage: 21, ot_wage: 31.5 },
  { id: 79, name: "Uriel Mandujano", company: "Construction", crew: "Yard", wage: 28, ot_wage: 42 },
  { id: 80, name: "Victor Tipaz Yat", company: "Landscape", crew: "Cesear", wage: null, ot_wage: null },
  { id: 81, name: "Victor Zacarias", company: "Landscape", crew: "Cesear", wage: 16, ot_wage: 24 },
  { id: 82, name: "Walter Perez", company: "Construction", crew: "Jairo", wage: 23, ot_wage: 34.5 },
  { id: 83, name: "Willie Cotton", company: "Construction", crew: "Driver", wage: 21, ot_wage: 31.5 },
  { id: 84, name: "Wilson Alonso", company: "Landscape", crew: "Wilson", wage: 22, ot_wage: 33 },
  { id: 85, name: "Yoandry Pelegrino", company: "Construction", crew: "Martin", wage: 20, ot_wage: 30 },
  { id: 86, name: "Jose Reyes", company: "Construction", crew: "Miscellaneous", wage: null, ot_wage: null },
  { id: 87, name: "Julian Mantilla", company: "Construction", crew: "Pavon", wage: 18, ot_wage: 27 },
  { id: 88, name: "Yader Martinez", company: "Landscape", crew: "Moises", wage: null, ot_wage: null },
  { id: 89, name: "Josue Aguirre Morales", company: "Landscape", crew: "Moises", wage: null, ot_wage: null },
];

export const crews = {
  Construction: ["Omar","Waldo","Jose L","Black","Tony","Marco","Jairo","Martin","Gambino","Driver","Miscellaneous","Yard","Hugo","Cesear","Pavon"],
  Landscape: ["Wilson","Noel","Ricardo","Erving","Defino","Moises","Nobel","Cesear Old","Cesear"]
};
